### ISSUE TITLE
    action_shape.append(content.n) AttributeError: 'Box' object has no attribute 'n'

### ISSUE THREAD

**Issue by azyslzp** [starry-sky6688/MADDPG#1]
Hi, when I first run the `python main.py --scenario-name=simple_tag --evaluate-episodes=10`, I met the problem as :
`    action_shape.append(content.n) AttributeError: 'Box' object has no attribute 'n'`
Thanks a lot~

**Comment by starry-sky6688** [comment]
Hi, I'm sorry that I also don't know why,  this code can run successfully on my meachine.

'content.n' is the number of actions for one agent, maybe because of the version of the partical environment?

**Comment by sampleargmax** [comment]
This issue can be solved by uninstalling the current openai PE and install the new openai PE in starry's link.

**Comment by sampleargmax** [comment]
By the way, and the gym version should be controlled to gym==0.10.5

**Comment by tekier** [comment]
> This issue can be solved by uninstalling the current openai PE and install the new openai PE in starry's link.

Hi, I am currently experiencing the same issue. What exactly is OpenAI PE and how can I find it? :-)

**Comment by a2nath** [comment]
Same issue on v0.26.2
