### ISSUE TITLE
is there anyone has excuted this repository? 

### ISSUE THREAD

**Issue by tanxiangtj** [starry-sky6688/MADDPG#10]
is there anyone has excuted this repository? how about the performance? i cannot get convergence in my case.

**Comment by hccz95** [comment]
hello, I tried simple_spread and got convergence, however, the evaluation performance is every bad

**Comment by starry-sky6688** [comment]
> hello, I tried simple_spread and got convergence, however, the evaluation performance is every bad

This issue has been solved in https://github.com/starry-sky6688/MADDPG/issues/13
