### ISSUE TITLE
AttributeError: 'MultiDiscrete' object has no attribute 'n'

### ISSUE THREAD

**Issue by hzxwonder** [starry-sky6688/MADDPG#11]
The job is wonderful! But when I want to run "python main.py --scenario-name=simple_world_comm --evaluate-episodes=10",it show me an error like this, it seems that it can't deal with the problem with more than two kinds of agents.Is there anything I can do to solve the problem? Thank you!
![AttributeError](https://user-images.githubusercontent.com/52537483/141405503-eb46238c-2810-4b2e-918c-b19fa87cc801.jpg)

**Comment by Milad-Rakhsha** [comment]
I am also getting a similar error, I would greatly appreciate any help!

**Comment by starry-sky6688** [comment]
ISSUE: https://github.com/starry-sky6688/MADDPG/issues/1

**Comment by Lee-Chengze** [comment]
Is there anyone solve the problem?

**Comment by starry-sky6688** [comment]
Maybe you can refer to ISSUE: https://github.com/starry-sky6688/MADDPG/issues/1
