### ISSUE TITLE
关于GPU版本以及scenario问题

### ISSUE THREAD

**Issue by Fanniao727** [starry-sky6688/MADDPG#12]
1.请问有GPU版本实现？
2.这个代码只是针对simple_tag这个场景吗？
3.num_adversaries是不是只在simple_tag中有意义，在别的场景下，比如simple_spread下需要设置为0？

**Comment by starry-sky6688** [comment]
1. 使用GPU很简单，就是加几个.cuda()函数，把网络和tensor放到GPU上就行，百度一下就有
2. 可以用在MPE的其他scenario上，修改参数里的scenario-name
3. 这个具体看一下MPE的说明吧
