### ISSUE TITLE
simple_spread场景

### ISSUE THREAD

**Issue by hccz95** [starry-sky6688/MADDPG#13]
作者你好！我在simple_tag上运行算法有效果，但是在simple_spread上运行能收敛，但是学出的策略非常差，不知道你有没有在这个场景上做过测试？（我跑过openai的官方代码，是能训练出效果的，但是那边是tensorflow实现的，害怕后续改进的时候调试比较麻烦）

**Comment by starry-sky6688** [comment]
我只跑了simple_tag

我这里给任务设置了一个episode_limit，把任务变成了episode case；官方跑的场景应该是contiual case，你试试看是不是受这个影响，可能现在设置的episode_limit对于simple_spread过短了

**Comment by hccz95** [comment]
> 
感谢回答，官方代码也有一个episode_limit，默认是25。你的代码默认是100，我改成25之后也能在simple_spread训练出效果了，这是不是说明100对于simple_spread太大了？

**Comment by starry-sky6688** [comment]
应该是
