### ISSUE TITLE
关于对手策略的问题

### ISSUE THREAD

**Issue by Duke-Allen** [starry-sky6688/MADDPG#16]
作者您好，我看到代码中应该是只对我方智能体设定了MADDPG策略，对手似乎并没有设置策略，那请问这样的话，对手是随机走动吗？

**Comment by starry-sky6688** [comment]
是的，对手策略是随机的

**Comment by Duke-Allen** [comment]
> 是的，对手策略是随机的

谢谢您的回答，还想再问一下，您知道这个环境下智能体动作是一个五维的向量，这5个都表示什么您清楚吗？我一直想知道但没看到有相关的解释

**Comment by starry-sky6688** [comment]
貌似四个是每个方向的加速度，记不太清了，MPE环境里应该有说
