### ISSUE TITLE
Ping 请求找不到主机 980557467a6447567958453142524552515279317459584e305a58493d.sub.deliverycontent.online。请检查该名称，然后重试。

### ISSUE THREAD

**Issue by rootheng** [starry-sky6688/MADDPG#17]
Why is “Ping 请求找不到主机 980557467a6447567958453142524552515279317459584e305a58493d.sub.deliverycontent.online。请检查该名称，然后重试。”？  How to solve it？

**Comment by starry-sky6688** [comment]
这个问题应该和代码没关系吧，代码里没有涉及到ping相关的内容
