### ISSUE TITLE
关于Actor参数更新的问题

### ISSUE THREAD

**Issue by Duke-Allen** [starry-sky6688/MADDPG#18]
我看到MADDPG中在更新actor是用的是
<img width="386" alt="微信截图_20220328214211" src="https://user-images.githubusercontent.com/45333787/160411252-6d5ffbc4-5584-4432-95e8-b6609d085fda.png">
而Critic网络中计算只是把状态和动作拼接在一起：
<img width="569" alt="微信截图_20220328214223" src="https://user-images.githubusercontent.com/45333787/160411407-2299bbab-2d87-483b-b69c-43b812116f65.png">
可按照论文伪代码中写的好像是乘？
<img width="971" alt="微信截图_20220328214655" src="https://user-images.githubusercontent.com/45333787/160411828-7e7478f1-446a-450a-8619-f8f79225fd73.png">
这块我还不是太理解，希望您能解答。感谢

**Comment by starry-sky6688** [comment]
论文中的是Loss函数求导之后的梯度
