### ISSUE TITLE
为什么这里maddpg/maddpy.py里 其他agent的动作不变呢，王树森老师的《深度强化学习》书本里面说是要变的，请您解答一下，感谢~

### ISSUE THREAD

**Issue by zzhuncle** [starry-sky6688/MADDPG#19]
![image](https://user-images.githubusercontent.com/57178872/161753469-f1a7230c-2046-45b0-966b-b755f1c09381.png)
![image](https://user-images.githubusercontent.com/57178872/161754117-c8fac754-1a07-49f3-92d3-167d4177cd6b.png)

**Comment by starry-sky6688** [comment]
你说的这个书上应该是改进过的，MADDPG的论文里，其他agent的动作是不变的，你看一下论文里的伪代码就知道了；

另外你还可以去看一下MAAC，应该也提到了MADDPG的这个问题

**Comment by zzhuncle** [comment]
> 

谢谢了，我看到了，MAAC还用了自注意力、SAC、COMA，大杂烩，现在还在看MADDPG和MAAC，我感觉是不是过时了hhh，想问一下大佬最近有啥推荐的MARL的论文看一看~

**Comment by starry-sky6688** [comment]
我也有段时间没看最新的MARL论文了，去看看NIPS和ICML里相关的吧，知乎搜，有人会把这些会议的强化学习论文列出来

**Comment by zzhuncle** [comment]
> 

谢谢~
