### ISSUE TITLE
RuntimeWarning: invalid value encountered in logaddexp

### ISSUE THREAD

**Issue by Duke-Allen** [starry-sky6688/MADDPG#20]
运行这个环境的时候您有遇到输出这个警告吗？
![QQ截图20220420174753](https://user-images.githubusercontent.com/45333787/164201188-bcf3b76a-0c8b-4534-aaaf-70900cf67a89.png)
这个似乎是MPE环境中`core.py`出现的问题，您知道怎么解决吗

**Comment by starry-sky6688** [comment]
我还没有遇到过这个问题

**Comment by Duke-Allen** [comment]
> 我还没有遇到过这个问题

好的感谢
