### ISSUE TITLE
关于训练时间

### ISSUE THREAD

**Issue by Syy-99** [starry-sky6688/MADDPG#21]
请问你给的model下的agent参数是在图片横坐标多少episode后得到的模型呢？最终reward可以达到多少？
是将所有time-steps = 2000000,走完后得到的模型吗？还是说通过加载每次的time-steps完成后的模型，然后多次运行了程序获得的最终模型呢？

**Comment by starry-sky6688** [comment]
额，这个项目貌似我没放图片，你说的是啥意思呢，我刚刚还以为你问的是StarCraft那个项目

**Comment by Syy-99** [comment]
我想问的是，你这个项目跑结果，最终收敛需要多久呀？
你项目中提供的model下的神经网络的参数似乎可以得到reward有大概1000，所以你这个参数是跑完time-step=200w后得到的结果吗？

**Comment by starry-sky6688** [comment]
收敛的话差不多一晚上吧，现在的模型参数是训练200W个time-step后的结果
