### ISSUE TITLE
target_network里 全连接层的weight/bias的require_grad=True

### ISSUE THREAD

**Issue by whisperww** [starry-sky6688/MADDPG#25]
https://github.com/starry-sky6688/MADDPG/blob/b50ca15c1a976eade3153f86852a457159efc686/maddpg/maddpg.py#L69

**Comment by whisperww** [comment]
请问是在这里不希望target_network更新的意思吗, 好像with no_grad()并没有起到这个效果

**Comment by whisperww** [comment]
不好意思, 没问题了

**Comment by whisperww** [comment]
请问这个地方为什么with torch.no_grad了,然后又对tensor进行了detach()呀

**Comment by starry-sky6688** [comment]
随手以防万一了一下，没有特殊的含义......
