### ISSUE TITLE
大佬请问这边当我先更新critic时再更新actor（论文是这样的）这个会报因为inplace操作导致梯度的更新失败。。真的改不出来了

### ISSUE THREAD

**Issue by xiaobingbuhuitou** [starry-sky6688/MADDPG#27]
self.critic_optim.zero_grad()
        critic_loss.backward()
        self.critic_optim.step()

        self.actor_optim.zero_grad()
        actor_loss.backward()
        self.actor_optim.step()
当我把这个顺序调整后，这个会报错：因为inplace操作导致梯度的更新失败。。感激了

**Comment by starry-sky6688** [comment]
![image](https://user-images.githubusercontent.com/38175678/185831538-6bd65f70-76b8-495a-8f86-3af1a4b53ca6.png)

试一试把critic的更新放在这里呢？我估计原因是：如果像你这样直接改顺序，前面的actor_loss使用critic_network计算了梯度，但是你接下来又把critic_network给更新了，此时actor_loss上那个梯度在pytorch看来已经过时了（虽然这个梯度不会更新critic_network）

**Comment by xiaobingbuhuitou** [comment]
好的谢谢了。ok

**Comment by mzyscholar** [comment]
大佬，我有个疑问，critic不应该是先更新之后指导actor更新吗，怎么actor也能再critic之前
