### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by Yiwen233** [starry-sky6688/MADDPG#29]
The multiagent  package is not found in utils.py,
def make_env(args):
    from multiagent.environment import MultiAgentEnv
    import multiagent.scenarios as scenarios

Is anything I got wrong?

**Comment by starry-sky6688** [comment]
You need to install [Multi-Agent Particle Environment](https://github.com/openai/multiagent-particle-envs) at first

**Comment by Yiwen233** [comment]
> You need to install [Multi-Agent Particle Environment](https://github.com/openai/multiagent-particle-envs) at first

谢谢！
