### ISSUE TITLE
你好，关于模型存储问题

### ISSUE THREAD

**Issue by xzxgg** [starry-sky6688/MADDPG#3]
maddpg文件中save_model函数存储名称和存储次数相关，但是init函数加载模型和存储次数无关，请问这个怎么理解呢？

**Comment by starry-sky6688** [comment]
这个你可以在arguments.py里设置model的路径 'model_dir'，相当于你不用管模型的存储，加载的时候直接指定路径就可以了。

**Comment by starry-sky6688** [comment]
加载模型是只需要加载一个最好的模型就可以，但是你训练的时候隔一段时间就保存一个模型才是最稳妥的。
