### ISSUE TITLE
AttributeError: 'Box' object has no attribute 'n'

### ISSUE THREAD

**Issue by wjh-scut** [starry-sky6688/MADDPG#31]
请问下，这个报错AttributeError: 'Box' object has no attribute 'n'怎么解决啊？
#1 这个提出的解决方法里说的OpenAI PE 指的是什么啊？

**Comment by starry-sky6688** [comment]
就是MPE环境——[Multi-Agent Particle Environment(MPE)](https://github.com/openai/multiagent-particle-envs)

**Comment by wjh-scut** [comment]
> 就是MPE环境——[Multi-Agent Particle Environment(MPE)](https://github.com/openai/multiagent-particle-envs)

好的，谢谢
