### ISSUE TITLE
world_comm问题

### ISSUE THREAD

**Issue by sdabj** [starry-sky6688/MADDPG#33]
请问 我在运行simple_tag的时候是没有问题的  但是在运行simple_world_comm的时候报错  AttributeError: 'MultiDiscrete' object has no attribute 'n'  有什么好的解决方法吗 谢谢您

**Comment by starry-sky6688** [comment]
大概率是MPE版本的问题，参考一下这个issue：https://github.com/starry-sky6688/MADDPG/issues/1

**Comment by sdabj** [comment]
> 大概率是MPE版本的问题，参考一下这个issue：#1



> 大概率是MPE版本的问题，参考一下这个issue：#1

试了一下 除了simple_reference 和simple_world_comm 都可以运行  可能是comm的影响  把comm功能关了就可以运行
