### ISSUE TITLE
关于参数共享机制的使用

### ISSUE THREAD

**Issue by wjh-scut** [starry-sky6688/MADDPG#34]
大佬你好，我想请问一下，如果想将参数共享机制运用到MADDPG中，那么是只需要创建一个Actor网络和一个Critic网络呢？还是应该创建一个Actor网络和n个Critic网络呢（n为智能体数量）？

**Comment by starry-sky6688** [comment]
一个Actor网络和一个Critic网络就可以了

**Comment by wjh-scut** [comment]
谢谢！
