### ISSUE TITLE
请问这个模型是用于连续动作场景还是离散动作场景呀

### ISSUE THREAD

**Issue by wxm2000** [starry-sky6688/MADDPG#35]
大佬你好，请问这个模型是用于连续动作场景还是离散动作场景呀。在代码中添加输出动作的取值，发现是连续的值。但是代码只有在env.discrete_action_space为True的场景下能跑得起来，如果改成False会报错。

**Comment by wxm2000** [comment]
![image](https://github.com/starry-sky6688/MADDPG/assets/122009478/2862fec2-b004-4af0-b99c-ec375e049ae2)
![image](https://github.com/starry-sky6688/MADDPG/assets/122009478/7710735f-1fea-487d-8aba-29dd15e1432e)
我在runner.py的文件的run函数中输出actions1，在evaluate文件输出actions2，输出结果如下图：
![image](https://github.com/starry-sky6688/MADDPG/assets/122009478/3ae22f01-fc08-461b-a8c5-e26e6ea2c7a6)
![image](https://github.com/starry-sky6688/MADDPG/assets/122009478/a530a392-e159-4d42-8acb-fcedf8c7b12f)

**Comment by wxm2000** [comment]
MADDPG似乎应该是作用于连续动作，但是我在main.py的env后面输出了env.discrete_action_space，显示为True，并且如果将它改为False会报错，请问这是什么原因呀
![image](https://github.com/starry-sky6688/MADDPG/assets/122009478/57adb81d-bc1d-4880-8a28-2c515b109ab2)
![image](https://github.com/starry-sky6688/MADDPG/assets/122009478/d9784b15-d877-4fc6-b820-0b8822af52a0)

**Comment by starry-sky6688** [comment]
用于连续动作场景的，至于env.discrete_action_space我也不太清楚，你可以去MPE里看看它实际的含义，可能和字面上的意思还有点差别？

**Comment by iceuan** [comment]
我也发现了这个问题，在utils.py里面，env.action_space是为5的，对应上、下、左、右和停止共五个动作，是属于离散的动作，也存在content.n属性（n属性用于离散的动作空间中，表示共有n种动作方式）；但是在环境动作中改为连续动作（即动作的数据结构为Box(...)的时候）会报错Box不存在属性n，不知道这个修改为连续动作空间后，utils.py中的action_shape该如何进行修改
![image](https://github.com/starry-sky6688/MADDPG/assets/84300519/84843887-c862-4ac4-ad32-57e1e803e8f8)
![image](https://github.com/starry-sky6688/MADDPG/assets/84300519/baddc047-5787-474d-9abe-5fd6cc1b313f)
