### ISSUE TITLE
how to use this project to train a new model?

### ISSUE THREAD

**Issue by Aib-star** [starry-sky6688/MADDPG#36]
how to use this project to train a new model?

**Comment by starry-sky6688** [comment]
Just delete the .pkl files in model/simple_tag/agent_{0,1,2}, and then use the following command

$ python main.py --scenario-name=simple_tag --evaluate=False

**Comment by Aib-star** [comment]
不对，我用了如下命令：python main.py --scenario-name=simple_tag。其实你的初始命令也一直在训练，因为evaluate的值默认为False。



At 2023-10-20 14:36:40, "starry-sky6688" ***@***.***> wrote:

Just delete the .pkl files in model/simple_tag/agent_{0,1,2}, and then use the following command

$ python main.py --scenario-name=simple_tag --evaluate=False
