### ISSUE TITLE
你好，可以问下关于mpe环境的相关问题吗

### ISSUE THREAD

**Issue by xzxgg** [starry-sky6688/MADDPG#4]
environment中reset_callback,observation_callback,done_callback这种不是参数吗？为啥会被当成函数调用呢？

**Comment by starry-sky6688** [comment]
不好意思才看到，我不太清楚你说的是哪里，可以把具体的代码段截个图吗？

**Comment by xzxgg** [comment]
我不知道这个评论怎么发图片，我发给您知乎私信了，可以帮我看下吗

**Comment by starry-sky6688** [comment]
好的，我去看看，一会知乎回你。
