### ISSUE TITLE
AttributeError: 'MultiDiscrete' object has no attribute 'n'

### ISSUE THREAD

**Issue by Tryici** [starry-sky6688/MADDPG#41]
When i run 'python main.py --scenario-name=simple_world_comm --evaluate-episodes=10', i encounter the error. 
I change the script from 'simple_tag' to 'simple_world_comm'.
How can i solve it, thanks.

**Comment by starry-sky6688** [comment]
Maybe you can refer to issue https://github.com/starry-sky6688/MADDPG/issues/1
