### ISSUE TITLE
关于参数问题

### ISSUE THREAD

**Issue by MonaHe123** [starry-sky6688/MADDPG#43]
作者您好，我看您的代码在AC网络定义的时候，定义了max_action，并将其赋值为high_action，我看其他文件中high_action的值为1，那么AC定义文件中的max_action似乎没有改变动作或者输出值。想请教一下为什么要定义一个max_action?

**Comment by starry-sky6688** [comment]
max_action和high_action是一个意思，只是为了对网络中输入的action进行归一化

**Comment by MonaHe123** [comment]
好嘞好嘞，谢谢您！




-----原始邮件-----
发件人:starry-sky6688 ***@***.***>
发送时间:2024-04-15 09:36:27 (星期一)
收件人: starry-sky6688/MADDPG ***@***.***>
抄送: MonaHe123 ***@***.***>, Author ***@***.***>
主题: Re: [starry-sky6688/MADDPG] 关于参数问题 (Issue #43)






max_action和high_action是一个意思，只是为了对网络中输入的action进行归一化
