### ISSUE TITLE
纯小白提问

### ISSUE THREAD

**Issue by RL-is-too-difficult** [starry-sky6688/MADDPG#45]
模型训练完成后怎么加载模型看训练过程中的那种捕食动画呢？文件里有些好的程序吗，或者有相似的文件可以参考着写一下呢

**Comment by starry-sky6688** [comment]
你把evaluate改成True，运行的就是评估函数，这个里面会显示画面

环境里主要通过这一句来控制是否显示画面，train的时候不用，evaluate的时候用——https://github.com/starry-sky6688/MADDPG/blob/b50ca15c1a976eade3153f86852a457159efc686/runner.py#L72
