### ISSUE TITLE
Q网络的定义

### ISSUE THREAD

**Issue by MonaHe123** [starry-sky6688/MADDPG#46]
作者您好，我想问一下，就是在您的critic网络定义的时候考虑的状态是所有agent的状态吗，但是我看MADDPG的伪代码，每个agent的Q网络考虑的自己的状态和所有的动作，我有点不太明白，麻烦您指导一下~
![image](https://github.com/user-attachments/assets/0320e7a0-139d-4055-9431-c65ed26d350f)
![image](https://github.com/user-attachments/assets/2e1b0874-347a-4f75-bfc0-27e32d0be5ac)

**Comment by starry-sky6688** [comment]
1. 这里critic输入的是所有agent的状态、动作
2. 论文为代码里输入的也是所有agent的状态、动作；你是不是看错了，x代表的是全局状态，o才是每个agent的自己的观察

**Comment by MonaHe123** [comment]
是的是的，因为x加了一个智能体的index，我理解错了，谢谢您！

**Comment by starry-sky6688** [comment]
或许你可以再仔细看看，x的上标是j，i才是智能体的index......
