### ISSUE TITLE
run是学习的部分，evaluate是评估，那在哪里训练呢？

### ISSUE THREAD

**Issue by xzxgg** [starry-sky6688/MADDPG#5]
load模型重载的地方好像没用到，请问在哪用呢

**Comment by xzxgg** [comment]
另外为啥训练出来的model_spread里面只有两个智能体的模型？

**Comment by starry-sky6688** [comment]
1. maddpg.py 里， init()函数中会判断是否存在模型，如果存在则加载。  


2. 应该是model_spread中只有两个你需要控制的agent。
