### ISSUE TITLE
学习曲线先好后坏

### ISSUE THREAD

**Issue by wawachen** [starry-sky6688/MADDPG#8]
对于navigation task， 训练3个agent 去合作趋近每个目标，

![plt](https://user-images.githubusercontent.com/30148408/120087482-5c60ff00-c0e0-11eb-8ff3-207cc7e71258.png)

最后得到的训练曲线是上升后下降， 不知道是什么原因， 是因为训练的episodes不足吗？
对于cooperative的reward function 一般都是采用shared同一个reward的， 对于这个reward的设计有什么要求吗？举个例子， 对于navigation task， 它的reward是对于每个landmark 求最小的agent到他的距离， 为什么不能是 对于每个agent，求到最小的landmark的距离作为reward 了？

麻烦大佬赐教

**Comment by starry-sky6688** [comment]
1. 曲线降下来是正常的，因为是off-policy，你继续训练的话应该还会升上去
2. reward用全局的是因为能够直接反映出agent之间的相互影响，如果每个在agent有各自的奖励的话，这个奖励就需要更加复杂的设计，设计起来就比较困难了。比如你说的agent自己到landmark的距离作为奖励，那么这个奖励没法体现出它对于整个团队的贡献
