### ISSUE TITLE
epsilon 更新的问题

### ISSUE THREAD

**Issue by rmwor1d** [starry-sky6688/MADDPG#9]
https://github.com/starry-sky6688/MADDPG/blob/2c5a93fb2680daf93e0e5c75298574f34038cc01/runner.py#L62
是否应该改为 `self.epsilon = max(0.05, self.epsilon - 0.0000005)` 呢？

**Comment by starry-sky6688** [comment]
是的，谢谢你的提醒，已经改过来了

不过之前的实验结果应该还是没问题的，因为默认的noise和epsilon的初始值一样，然后下降速度也一样，导致我当时没发现这个问题
